Add changesets for changelog generation
spruceid/ssx pull request #2
Opened 2022-10-20 14:22 UTC by skgbafa

Changesets seems to be a great way to generate changelog for multiple packages while setting up for a nice release flow.

2022-10-21 13:33 UTC, Juliano1612 approved these changes

2022-11-08 18:30 UTC, 44203 requested changes
Can we add a CONTRIBUTING.md to the project root that documents briefly using changesets to cut a release?

2022-11-08 20:50 UTC, w4ll3 approved these changes

2022-11-08 20:57 UTC, 161chihuahuas approved these changes

2022-11-08 21:30 UTC, merged