Rename references to recap.
spruceid/ssx pull request #4
Opened 2022-10-26 09:20 UTC by cobward

CapGrok was renamed to ReCap. These are the only references to CapGrok in the codebase. There are also references in the generated documentation, but I assume those would get fixed automatically with this merged?

2022-10-26 09:24 UTC, skgbafa approved these changes
Run `yarn documentation` to generate the updated documentation. It may have other changes if it hasn’t been run in a while. Otherwise the changes look good to me

2022-10-26 20:49 UTC, skgbafa requested changes
After further thought and discussion, we should run `yarn documentation` on the documentation branch where the changes captured are specific to that branch. Running this command on a branch that is not up to date (or that has unpublished changes) could affect the public documentation!

I know I requested you run it, but please remove those extra changes 😄

2022-10-27 12:20 UTC, Juliano1612 approved these changes

2022-10-28 12:40 UTC, skgbafa approved these changes

2022-10-28 16:41 UTC, merged