Improve standalone usage of SSX Gnosis Extension
spruceid/ssx pull request #69
Opened 2023-01-27 19:18 UTC by Juliano1612

# Description

`ssx-gnosis-extension` helps to enable the DAO Login functionality by creating a modal and enabling selectors for end users. Because the module fetches the list of delegates for the sole purpose of displaying a selection UX to the user, the selected option is not currently matched against the retrieved list of delegates. This important security check is performed in SSX Server via a call to SiweMessage.verify, and these modules were designed to work together.
This change improves the experience for developers who want to use `ssx-gnosis-extension` standalone (that is, without SSX Server) by adding extra checks on the client side to help with UX. However, the server side MUST still check for delegate inclusion by using SiweMessage.verify or similar immediately after sign-in.

# Type

- [ ] Improvement

# Diligence Checklist

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2023-01-27 19:18 UTC, w4ll3 approved these changes

2023-01-30 17:19 UTC, 44203 requested changes, later dismissed

2023-01-30 17:19 UTC, 44203 commented on packages/ssx-gnosis-extension/src/modal.ts
> +    if (!option || [...delegators, this._connectedAddress].filter(delegator => option === delegator).length !== 1) {
The visual comprehension here should be improved. Recommend assigning the result of that filter result/condition check to a variable and referencing the variable in the conditional block.

2023-01-31 16:54 UTC, skgbafa approved these changes
The logic here looks sounds and works as expected in the gnosis component when tested in SSX. I did not test as a standalone component however

2023-01-31 17:52 UTC, merged