Social app
spruceid/ssx pull request #71
Opened 2023-01-31 01:10 UTC by franklovefrank

# Description

example SSX-powered app that has a universal post feed, and lets signed-in users add a post. This version is configured to run locally and does not persist state

# Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Diligence Checklist

(Please delete options that are not relevant)

- [ X] This change requires a documentation update
- [X ] I have performed a self-review of my code
- [X ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings

2023-02-07 17:41 UTC, Juliano1612 requested changes

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/README.md
> +# ssx-test-dapp
```suggestion
# ssx-test-social
```

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/src/interfaces/iPost.ts
> +
```suggestion
```

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/src/interfaces/iPostContext.ts
> +
```suggestion
```

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/src/components/AccountInfo.tsx
> +function AccountInfo({ address, delegator }: { address: string, delegator?: string }) {
```suggestion
function AccountInfo({ address }: { address: string }) {
```

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/src/components/NewPost.tsx
> +import { TextField, Button, InputAdornment, IconButton } from '@material-ui/core';
```suggestion
import { TextField, InputAdornment, IconButton } from '@material-ui/core';
```

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/src/components/SinglePost.tsx
> +import React from 'react';
```suggestion
```

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/src/components/Feed.tsx
> +import { useContext, useEffect, useState } from 'react';
```suggestion
import { useContext, useEffect } from 'react';
```

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/src/ssx.config.js
> +    //resolveEns: true,
```suggestion
```

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/hardhat.config.ts
> +/**
Do we need to use Hardhat on this project? I removed the dependency and the hardhat.config.ts locally and the app is still working.

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/package.json
> +    "hardhat": "^2.12.6",
Same here

2023-02-07 17:41 UTC, Juliano1612 commented on examples/ssx-test-social/.env.example
> +CONTRACT_ADDRESS = "0x<your contract address>"
```suggestion
```

Same about Hardhat here

2023-02-07 18:09 UTC, w4ll3 commented on examples/ssx-test-social/src/App.test.tsx
> +import React from 'react';
This can be deleted

2023-02-07 18:09 UTC, w4ll3 commented on examples/ssx-test-social/src/components/Feed.tsx
> +  if (posts && posts.length > 0) {
```suggestion
  if (posts?.length > 0) {
```

2023-02-07 18:09 UTC, w4ll3 commented on examples/ssx-test-social/src/components/Feed.tsx
> +  useEffect(() => {
do you really need this hook?

2023-02-07 18:09 UTC, w4ll3 commented on examples/ssx-test-social/src/components/NewPost.tsx
> +    const address = (ssxProvider instanceof SSX && typeof ssxProvider.address() !== 'undefined')
can't this all be resumed to `ssxProvider?.address()`?

2023-02-17 16:33 UTC, Juliano1612 approved these changes
Looks good to me!

2023-02-17 16:33 UTC, Juliano1612 commented on examples/ssx-test-social/package.json
> +     "@emotion/react": "^11.10.5",
```suggestion
    "@emotion/react": "^11.10.5",
```

2023-02-17 16:33 UTC, Juliano1612 commented on examples/ssx-test-social/src/components/Feed.tsx
> +import { useContext} from 'react';
```suggestion
import { useContext } from 'react';
```

2023-02-21 12:45 UTC, Juliano1612 approved these changes

2023-02-21 13:39 UTC, w4ll3 approved these changes

2023-02-21 14:53 UTC, obstropolos commented on examples/ssx-test-social/README.md
> +This is a simple social media that demonstrates the functionality of SSX. It is configured to run locally and does not persist state between instances.
"social media" -> "social media dapp"

2023-03-06 14:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spruceid/ssx?pullRequest=71) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spruceid/ssx?pullRequest=71) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spruceid/ssx?pullRequest=71) it.</sub>

2023-03-07 16:15 UTC, obstropolos commented
Closing - will be consolidated under a repository - `ssx-examples`

2023-03-07 16:15 UTC, closed without merging