nonce bug fix
spruceid/ssx pull request #74
Opened 2023-02-03 18:31 UTC by franklovefrank

# Description

fixes bug described here https://github.com/spruceid/ssx/issues/70

# Type

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Diligence Checklist

- [x ] I have performed a self-review of my code
- [ x] My changes generate no new warnings

2023-02-06 19:19 UTC, Juliano1612 requested changes

2023-02-06 19:19 UTC, Juliano1612 commented on packages/ssx-server-middleware/src/express/endpoints.ts
>        res.status(200).json({ ...req.session });
```suggestion
```
It is already being done on line 90

2023-02-06 19:19 UTC, w4ll3 reviewed
Just awaiting for requested changes

2023-02-07 13:21 UTC, Juliano1612 approved these changes

2023-02-07 13:46 UTC, w4ll3 approved these changes

2023-02-07 22:19 UTC, merged